name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Setup job variables
        uses: allenevans/set-env@v2.0.1
        with:
          LAZARUS_VERSION: 2.0.10
          FPC_VERSION: 3.2.0
      - uses: actions/checkout@v3
      - name: Get Lazarus dependencies
        shell: bash
        id: get-dependencies
        run: echo "::set-output name=dependencies::$(node ./.github/workflows/scripts/getPackages.js)"
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3.0.16
        with:
          lazarus-version: ${{ env.LAZARUS_VERSION }}
          include-packages: ${{ steps.get-dependencies.outputs.dependencies }}
      - name: Install 32bit compat
        shell: bash
        run: node ./.github/workflows/scripts/install32bitCompat.js
      - name: Build 32-Bit
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 32-bit" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Build 64-Bit
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Build 64-Bit O4 AVX2
        if: always()
        shell: cmd
        run: lazbuild --build-mode="Release 64-bit O4 AVX2" --no-write-project "Cheat Engine/cheatengine.lpi"
      - name: Zip artifact
        if: always()
        shell: cmd
        run: 7z a -tzip release.zip * -r
        working-directory: "./Cheat Engine/bin"
      - name: Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: "Cheat Engine/bin/release.zip"
